server:
  port: 8082

spring:
  application:
    name: profile-producer
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: userProfile:com.playbook.profileproducer.model.UserProfile

management:
  endpoints:
    web:
      exposure:
        include: health
