server:
  port: 8083

spring:
  application:
    name: shipping-service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: >-
          shippingInitiated:com.playbook.shipping.model.ShippingInitiated,
          orderCompleted:com.playbook.shipping.model.OrderCompleted,
          orderCancelled:com.playbook.shipping.model.OrderCancelled
    consumer:
      group-id: shipping-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted-packages: "com.playbook.*"
        spring.json.type.mapping: >-
          paymentCompleted:com.playbook.shipping.model.PaymentCompleted,
          paymentFailed:com.playbook.shipping.model.PaymentFailed,
          inventoryFailed:com.playbook.shipping.model.InventoryFailed

management:
  endpoints:
    web:
      exposure:
        include: health
