server:
  port: 8081

spring:
  application:
    name: versioned-consumer
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: versioned-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted-packages: "com.playbook.*"
        spring.json.type.mapping: orderEvent:com.playbook.consumer.model.OrderEventFull
        spring.json.use.type.headers: false

management:
  endpoints:
    web:
      exposure:
        include: health
