server:
  port: 8080

spring:
  application:
    name: catalog-producer
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: productCommand:com.playbook.producer.model.ProductCommand

management:
  endpoints:
    web:
      exposure:
        include: health
