server:
  port: 8080

spring:
  application:
    name: order-producer-v1
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderEvent:com.playbook.producerv1.model.OrderEventV1

management:
  endpoints:
    web:
      exposure:
        include: health
